### ISSUE TITLE
Abnormal battery drain when no network connection is available at stock refresh

### ISSUE THREAD

**Issue by ephphatha** [CaptainSpam/geohashdroid#66]
I was out at a location that had no phone reception (and no wifi) with my phone on a battery pack charging overnight. At around 11:30pm (between 11-12 according to the graph, 11:30 local time is when the stock refresh occurs for me) the phone battery started depleting despite being on a charger. The notification area was rapidly flashing the "Downloading stock data" message from Geohash Droid. I ended up having to turn the phone off to get it to charge, then wait until I got to a point where I had reception for it to complete the download.

I checked the battery usage as reported by Android and the process it reported as being responsible for the battery usage was something along the lines of "network monitor service" - I don't recall the service name but I'm running stock android so it would have to be a core service.

I'm not 100% sure Geohash Droid is to blame but as far as I could tell I had no other apps running that require a network connection. I suspect it might not be handling the case where the connections are enabled but not active, assuming that's a different case to having wifi/cellular data disabled.

**Comment by CaptainSpam** [comment]
Okay, that's really weird.  That sounds like something's giving Geohash Droid the signal that there's a network connection when there isn't one, meaning it checks stocks, gives up, asks for network updates again, and immediately gets another signal that the connection's back.  I'll look over that part of the code again, but I thought I got everything right as far as Nougat-style network checks and callbacks are concerned.  I sure hope I didn't forget something obscure on that end.

**Comment by ephphatha** [comment]
Sorry, I should've mentioned originally but I'm still running Android 6.0.1 (Marshmallow) on a Nexus 5. I assume the Nougat-style API you're talking about is backwards compatible but there might be some incompatibility there.

**Comment by CaptainSpam** [comment]
Well, I guess I should clarify, the network checks I'm doing have been around since Lollipop, but they became *mandatory* with Nougat (that is, the older-style checks stopped working entirely).  Either way, that's what's being used on Marshmallow.

From everything I can see, I'm pretty sure I'm doing everything right on my end for network checks.  From the perspective of the app, what I'm using shouldn't care if the network was disabled manually or simply nonexistent where you are, nor even what type of network you're connected to (though that last one is *possible*, I just don't tell it to make that a concern that for such a small amount of data that I'm fetching), so I doubt that'd be doing anything strange.  Unless I hear different, this sounds like a weird glitch deeper in the system.  Has this happened again under the same circumstances, by any chance?

Now, I don't see anything else I can do to prevent it from waking up like that, but, as a stopgap measure, it looks like I CAN tell it to delay checks for a few seconds every time it's scheduled.  That way, at the very least it shouldn't keep hammering the notification you were seeing quite as fast, which might stave off the battery issues until it gets definitively clear if it's my code or something on Android's side.  I'll look into testing that next.

**Comment by ephphatha** [comment]
I still haven't been able to replicate the exact situation that caused this issue the first time, however I'm noticing Adobe behaviour that I think might be related or a similar cause.

Around the time of stock refresh I get a notification that rapidly appears and disappears in the silent notification area. This notification is never active long enough for me to see what it says but given the timing I suspect it's the geohash droid fetching stock data notification. Annoyingly the rapidly toggling notification causes the whole notifications list to scroll up due to it resizing with the item being added and removed.

I'm currently using a Nokia 7 plus running Android 10 with the Android One base, if there's any specific testing you'd like me to try I can probably work it out.

**Comment by CaptainSpam** [comment]
Hm, that's quite strange.  The only time that notification channel should be used is if the prefetcher is active.  A notification goes up once it starts working and goes away when it's done, whether or not it was successful (there shouldn't be anything displayed if it's waiting for the network or snoozing in the case of some other network error).  And from what you're saying about how some notification kept popping up and going away rapidly, it sounds like, for some reason, the fetcher is waking up, determining it can't (or doesn't need to) fetch, stopping, and immediately getting woken back up.

I might have one or two other things I can check regarding that, though one thing I can do right away (in the commit just referenced here) is change the way wake-when-connection-returns happens.  That might help a bit, but there's something else I might be able to look into in order to stop it from pinging the notification if it doesn't need to go to the network at all.

**Comment by CaptainSpam** [comment]
Okay... I've just pushed a new release, both to here and to the Play Store (pending the usual review delay in the latter case).  In it, I've refactored how the entire wait-for-network-connection part of the stock prefetcher works, and hopefully this new way should be a lot less of a drain on the battery.  Maybe.  I hope?

Let me know if it did the trick!

**Comment by jonathanwcrane** [comment]
Hey @CaptainSpam I just want to chime in and say how great it is that you're actively developing this app.  I truly appreciate your service and I owe you at least a 🍺 .  Thanks!

**Comment by ephphatha** [comment]
Unfortunately I'm still getting rapid notifications with 0.9.5.3 😣. Had it happen just now at 12:30 am Monday, 63 notifications from the pre-fetcher but from the date the app should know there's no stock data available. I'll try find a way to reproduce it properly since it makes no sense to me why it's going off when it does.

**Comment by CaptainSpam** [comment]
Dang.  I was hoping that'd do it.

There's other things I can try, though.  Next up, I might set it up to stall for at least minute or so after a failure before it starts listening for network events again.  That seems like a bit of a cheap hack, but it might do the job with little disruption otherwise.

Another thing I can do is cook up a debug build off of the current version for you to install (based on the "logcat" branch, if you want to check; I'd need to rebase it up to the current release first, of course).  That's got an extra option in it that can help get logging data if need be.  That might get me more info.

I'll see what I can do with that.

**Comment by ephphatha** [comment]
Looks like the latest fix worked to keep the notification active 🎉

The behaviour I'm seeing now is the fetching stock notification appears (once) and stays open until it's successful. It does stay open longer than expected though, just now it was showing 40 minutes since it appeared. The notification disappeared immediately when I opened the app so I assume it had completed at some point much earlier.

I also have not been able to reproduce the battery drain issue so I think that can be closed, given the stock fetching plays nicer I'm happy to assume it's been fixed.

**Comment by CaptainSpam** [comment]
It did?  Huh, that's sort of surprising, the most recent versions didn't touch the notification/alarm code, I thought.

Still, glad to hear it's working right!  Not quite sure why the notification isn't disappearing consistently, but it's not dumping a ton of rapid-fire notifications on you, so that's much better.

Thanks for the bug report!
